// Need G4P library
import g4p_controls.*;


public void setup(){
  size(480, 320, JAVA2D);
  createGUI();
  customGUI();
  // Place your setup code here
  
}

public void draw(){
  background(230);
  
}

// Use this method to add additional statements
// to customise the GUI controls
public void customGUI(){

}

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:605329:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:605329:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:215764:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:215764:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 165, 4, 33, 22);
  button1.setText("Go");
  button1.addEventHandler(this, "button1_click1");
  textfield1 = new GTextField(this, 4, 4, 157, 23, G4P.SCROLLBARS_NONE);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GTextField textfield1; 