/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

/*
public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:605329:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:605329:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:215764:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:215764:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 165, 4, 33, 22);
  button1.setText("Go");
  button1.addEventHandler(this, "button1_click1");
  textfield1 = new GTextField(this, 4, 4, 157, 23, G4P.SCROLLBARS_NONE);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GTextField textfield1; 

*/